modLoader="javafml"
loaderVersion="[52,)"
license="MIT"
issueTrackerURL="https://github.com/kintil555/thebackrooms/issues"

[[mods]]
    modId="backrooms"
    version="1.0.0"
    displayName="The Backrooms"
    description='''
        Experience the horror of The Backrooms.
        Fall through null zones to escape into the endless yellow hallways.
        Some chunks have ghost blocks - blocks you can walk through that lead to the void below.
    '''
    authors="BackroomsMod"

[[dependencies.backrooms]]
    modId="forge"
    mandatory=true
    versionRange="[52.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.backrooms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
